Vagrant.require_version ">= 2.2.0"

# Configuration
SSH_PRIVATE_KEY="~/.ssh/id_vagrant_rsa"
SSH_PUBLIC_KEY="~/.ssh/id_vagrant_rsa.pub"

# use two digits id below, please
nodes = [
  { :hostname => 'master',  :ip => '10.240.0.20', :id => '10' },
  { :hostname => 'node1',   :ip => '10.240.0.21', :id => '11' }
  # { :hostname => 'node2',   :ip => '10.240.0.22', :id => '12' }
]


Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.box_version = "1811.02"
    config.ssh.insert_key = false
    config.ssh.private_key_path = [SSH_PRIVATE_KEY, "~/.vagrant.d/insecure_private_key"]
    config.vm.provision "file", source: SSH_PUBLIC_KEY, destination: "~/.ssh/authorized_keys"
    nodes.each do |node|
      config.vm.define node[:hostname] do |nodeconfig|
        nodeconfig.vm.hostname = node[:hostname]
        nodeconfig.vm.network "private_network", ip: node[:ip]
        nodeconfig.vm.provider :virtualbox do |vb|
          vb.name = node[:hostname]+".kube"
          vb.memory = 2048
          vb.cpus = 2
        end
        nodeconfig.vm.synced_folder ".", "/vagrant", :mount_options => ["dmode=777", "fmode=666"]
        nodeconfig.vm.provision :shell, :path => "scripts/install.sh"
      end
    end
end
